conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: ./data/samples/

measurement:
  operator:
    name: style_retrieval
    #in_shape: !!python/tuple [1, 3, 512, 512]
    #scale_factor: 1
  
  noise: 
    name: gaussian
    sigma: 0.05
